apiVersion: secrets.hashicorp.com/v1alpha1
kind: VaultConnection
metadata:
  name: vaultconnection-demo
  namespace: vault-demo
spec:
  address: https://vault-private-vault-9640d9a6.d9c88c70.z1.hashicorp.cloud:8200
---
apiVersion: secrets.hashicorp.com/v1alpha1
kind: VaultAuth
metadata:
  name: vaultauth-demo
  namespace: vault-demo
spec:
  vaultConnectionRef: vaultconnection-demo
  namespace: admin
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: demo-role
    serviceAccount: default
---
apiVersion: secrets.hashicorp.com/v1alpha1
kind: VaultStaticSecret
metadata:
  name: vaultstaticsecret-demo
  namespace: vault-demo
spec:
  vaultAuthRef: vaultauth-demo
  namespace: admin
  mount: secret
  name: demo/config
  type: kv-v2
  refreshAfter: 5s
  rolloutRestartTargets:
    - kind: Deployment
      name: vault-demo-app
  destination:
    name: secret-demo
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-demo
  namespace: vault-demo
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-demo-app
  namespace: vault-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-demo-app
  template:
    metadata:
      labels:
        app: vault-demo-app
    spec:
      containers:
        - name: nginx
          image: nginx
          volumeMounts:
            - name: secrets
              mountPath: "/etc/secrets"
              readOnly: true
      volumes:
        - name: secrets
          secret:
            secretName: secret-demo
            optional: false
